apiVersion: v2
name: zammad-ldap-sync-chart
version: 0.1.0
maintainers:
  - name: kl.mueller
    email: kl.mueller@muenchen.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/zammad-ldap-sync-chart
icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
