apiVersion: v1
kind: Secret
metadata:
  name: zammad-ldap-sync
type: Opaque
data:
  spring.mail.password: {{ .Values.ldapSync.applicationYML.spring.mail.username }}
  spring.mail.username: {{ .Values.ldapSync.applicationYML.spring.mail.username }}
  zammad.token: {{ .Values.ldapSync.zammadToken }}