apiVersion: v1
kind: Secret
metadata:
  name: zammad-ldap-sync
type: Opaque
data:
  spring.mail.password: {{ .Values.ldapSync.applicationYML.spring.mail.password | b64enc }}
  spring.mail.username: {{ .Values.ldapSync.applicationYML.spring.mail.username | b64enc}}
  zammad.token: {{ .Values.ldapSync.zammadToken | b64enc}}