apiVersion: v1
kind: Secret
metadata:
  name: zammad-ldap-sync
type: Opaque
data:
  spring.mail.password: UmVwbGFjZVdpdGhNYWlsQWNjb3VudFBhc3N3b3JkCg==
  spring.mail.username: UmVwbGFjZVdpdGhNYWlsQWNjb3VudFVzZXJuYW1lCg==
  zammad.token: UmVwbGFjZVdpdGhaYW1tYWRBY2Nlc3NUb2tlbgo=