apiVersion: v1
kind: Secret
metadata:
  name: zammad-ldap-sync
type: Opaque
data:
  spring.mail.password: ReplaceWithMailAccountPassword
  spring.mail.username: ReplaceWithMailAccountUsername
  zammad.token: ReplaceWithZammadAccessToken