apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daveSelfservicePortal.fullname" . }}
  labels: 
    {{- include "dave.labels" . | nindent 4 }}
data:
  {{- with .Values.daveSelfservicePortal.applicationYML }}
  application.yml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
