apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dave.fullname" . }}-frontend-client-secret
  labels: 
    {{- include "dave.labels" . | nindent 4 }}
data:
  {{- with .Values.global.keys }}
    {{- toYaml . | nindent 12 }}
  {{- end}}