{{- if .Values.daveBackend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dave.serviceAccountName" . }}
  labels:
    {{- include "dave.labels" . | nindent 4 }}
  {{- with .Values.daveBackend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
