#daveBackend:
#  service:
#    port: 8778

## https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch
elasticsearch:
  global:
    imageRegistry: "dockerhub.muenchen.de"
    storageClass: "thin-csi"
  sysctlImage:
    enabled: false
  master:
    resources:
      limits:
        cpu: 2
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    replicaCount: 1
  coordinating:
    replicaCount: 0
  data:
    replicaCount: 0
  ingest:
    replicaCount: 0

#daveBackend:
#  elasticsearch:
#    # enable/disable elasticsearch chart dependency
#    enabled: true
#    # host env var is only used when zammadConfig.elasticsearch.enabled is false
#    host: dave-elasticsearch
#    initialisation: true
#    pass: "XXXXXXXXXXXXXXXXXXXXXxxxxx"
#    port: 9200
#    reindex: true
#    schema: http
#    user: ""
