global:
  credentials: 
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXX

## https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch
elasticsearch:
  global:
    imageRegistry: "dockerhub.muenchen.de"
    storageClass: "thin-csi"
  sysctlImage:
    enabled: false
  master:
    resources:
      limits:
        cpu: 2
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    replicaCount: 1
  coordinating:
    replicaCount: 0
  data:
    replicaCount: 0
  ingest:
    replicaCount: 0

admin-portal:
  extraEnvVars:
    HAZELCAST_GROUP_NAME: dave-adminportal-apigateway-service-session_replication_group
    HAZELCAST_INSTANCE: dave-adminportal-apigateway-service-hazl_instance
    HAZELCAST_OPENSHIFT_SERVICE_NAME: dave-adminportal-apigateway-service
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: dev
  route:
    enabled: true
    targetPort: service

backend:
  extraEnvVars:
    env:
      GC_MAX_METASPACE_SIZE: "256"
      HAZELCAST_GROUP_NAME: dave-backend-service-hazl_group
      HAZELCAST_INSTANCE: dave-backend-service-hazl_instance
      HAZELCAST_OPENSHIFT_SERVICE_NAME: dave-backend-service
      JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit
        -Xmx1g --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
        --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
        --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      SERVER_PORT: "8080"
      SPRING_PROFILES_ACTIVE: dev
      TOMCAT_GRACEFULSHUTDOWN_PRE_WAIT_SECONDS: "40"
      #HAZELCAST_JET_ENABLED: "true"

    email:
      DAVE_EMAIL_ADDRESS: ex.bayr@muenchen.de
      DAVE_EMAIL_RECEIVER_CUT_EMAIL_BODY_LINE_BEGINS_WITH_STRINGS: 'Von:;Gesendet:'
      DAVE_EMAIL_RECEIVER_CUT_EMAIL_BODY_LINE_CONTAINS_STRINGS: Landeshauptstadt München;Schuh&Co.GmbH;-----Ursprüngliche Nachricht-----;dave-dev@muenchen.de
      DAVE_EMAIL_RECEIVER_UPDATE_INTERVAL: "30000"

  credentials:
    SPRING_DATASOURCE_URL: jdbc:postgresql://dave-postgresql:5423/dave_db
    SPRING_DATASOURCE_USERNAME: dave_user
    SPRING_DATASOURCE_PASSWORD: XXXXXXXXXXXXXXXXXXXXXXXXXX
    DAVE_EMAIL_PASSWORD: XXXXXXXXXXXXXXXXXXXXXXXXXX
    ELASTICSEARCH_HOST: dave-elasticsearch
    ELASTICSEARCH_PASSWORD: XXXXXXXXXXXXXXXXXXXXXXXXXX
  
  route:
    enabled: true
    targetPort: service

eai:
  extraEnvVars:
    GC_MAX_METASPACE_SIZE: "256"
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit -Xmx512m
    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
    MANAGEMENT_SERVER_PORT: "8079"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: dev
  route:
    enabled: true
    targetPort: service

frontend:
  extraEnvVars:
    HAZELCAST_GROUP_NAME: dave-frontend-apigateway-service-session_replication_group
    HAZELCAST_INSTANCE: dave-frontend-apigateway-service-hazl_instance
    HAZELCAST_OPENSHIFT_SERVICE_NAME: dave-frontend-apigateway-service
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: dev

  route:
    enabled: true
    targetPort: service

selfservice-portal:
  extraEnvVars:
    HAZELCAST_GROUP_NAME: dave-selfserviceportal-apigateway-service-session_replication_group
    HAZELCAST_INSTANCE: dave-selfserviceportal-apigateway-service-hazl_instance
    HAZELCAST_OPENSHIFT_SERVICE_NAME: dave-selfserviceportal-apigateway-service
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: dev
  route:
    enabled: true
    targetPort: service

postgresql:
  storageClass: "thin-csi"
    
  auth:
    username: dave_user
    password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    database: dave_db

  primary:
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
#    persistence:
#      storageClass: "thin-csi"

#  primary:
#    podSecurityContext:
#      enabled: false
#      fsGroup: ""
#    containerSecurityContext:
#      enabled: false
#      runAsUser: "auto"
#
#  readReplicas:
#    podSecurityContext:
#      enabled: false
#      fsGroup: ""
#    containerSecurityContext:
#      enabled: false
#      runAsUser: "auto"
#
#  volumePermissions:
#    enabled: false
#    securityContext:
#      runAsUser: "auto"
