# Default LHM specific values for dave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values
global:
  credentials: 
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-SECRET: XXXX-SECRET-XXXX

# Dave Backend
backend:
  # Environment Variables
  extraEnvVars:
    env:
      JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit
        -Xmx1g --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
        --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED
        --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
      KEYCLOAK_AUTH-SERVER-URL: https://ssodev.muenchen.de/auth
    # Dave Email Settings
    email:
      DAVE_EMAIL_RECEIVER_HOSTNAME: imap.muenchen.de
      DAVE_EMAIL_ADDRESS: dave-dev@muenchen.de
      DAVE_EMAIL_RECEIVER_CUT_EMAIL_BODY_LINE_CONTAINS_STRINGS: Landeshauptstadt München;Schuh&Co.GmbH;-----Ursprüngliche Nachricht-----;dave-dev@muenchen,
  # Credentials
  credentials:    
    DAVE_EMAIL_PASSWORD: XXXX-SECRET-XXXX
  # Volume for CA-Certfificates 
  extraVolumeMounts:
    - name: cacerts-lhm
      readOnly: true
      mountPath: /mnt
  extraVolumes: 
    - name: cacerts-lhm
      secret:
        secretName: cacerts-lhm
        defaultMode: 420  

# Dave Admin-Portal
admin-portal:
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    SPRING_CLOUD_GATEWAY_ROUTES_0_URI: https://ssodev.muenchen.de/    
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: https://ssodev.muenchen.de/auth/realms/${spring.realm}
  # Volume for CA-Certfificates 
  extraVolumeMounts:
    - name: cacerts-lhm
      readOnly: true
      mountPath: /mnt
  extraVolumes: 
    - name: cacerts-lhm
      secret:
        secretName: cacerts-lhm
        defaultMode: 420

# Dave EAI
eai:
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit -Xmx512m
  # Volume for CA-Certfificates   
  extraVolumeMounts:
    - name: cacerts-lhm
      readOnly: true
      mountPath: /mnt
  extraVolumes: 
    - name: cacerts-lhm
      secret:
        secretName: cacerts-lhm
        defaultMode: 420

# Dave Frontend
frontend:
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    SPRING_CLOUD_GATEWAY_ROUTES_0_URI: https://ssodev.muenchen.de/
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: https://ssodev.muenchen.de/auth/realms/${spring.realm}
  # Volume for CA-Certfificates 
  extraVolumeMounts:
    - name: cacerts-lhm
      readOnly: true
      mountPath: /mnt
  extraVolumes: 
    - name: cacerts-lhm
      secret:
        secretName: cacerts-lhm
        defaultMode: 420

# Dave Selfservice-Portal
selfservice-portal:
  # Environment variables
  extraEnvVars:
    JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/mnt/cacerts-lhm -Djavax.net.ssl.trustStorePassword=changeit
      --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens
      java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens
      java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED
      --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    SPRING_CLOUD_GATEWAY_ROUTES_0_URI: https://ssodev.muenchen.de/
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: https://ssodev.muenchen.de/auth/realms/${spring.realm}
  # Volume for CA-Certfificates  
  extraVolumeMounts:
    - name: cacerts-lhm
      readOnly: true
      mountPath: /mnt
  extraVolumes: 
    - name: cacerts-lhm
      secret:
        secretName: cacerts-lhm
        defaultMode: 420

# Elasticsearch
elasticsearch:
  global:
    imageRegistry: "dockerhub.muenchen.de"
